version: "3.8"

services:
  triton-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.triton
    ports:
      - "8000:8000" # HTTP
      - "8001:8001" # GRPC
      - "8002:8002" # Metrics
    volumes:
      - ./model_repository:/models
      - /tmp/trt_cache:/tmp/trt_cache
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - TRITON_MODEL_REPOSITORY=/models
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v2/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # Optional: client container for testing
  triton-client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    depends_on:
      - triton-server
    volumes:
      - ./client:/workspace/client
      - ./data:/workspace/data
    environment:
      - TRITON_URL=triton-server:8000
    profiles:
      - client
