services:
  triton-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dinov2-triton-server
    ports:
      - "8000:8000" # HTTP
      - "8001:8001" # GRPC
      - "8002:8002" # Metrics
    volumes:
      - ./models:/models
      - ./logs:/logs
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v2/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      model-builder:
        condition: service_completed_successfully

  # Service to build models (run once)
  model-builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    container_name: dinov2-model-builder
    volumes:
      - ./models:/workspace/models
      - .:/workspace/src
      - ./logs:/workspace/logs
    working_dir: /workspace/src
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - build
    command:
      ["bash", "-c", "python export_model_onnx.py && ./convert_to_tensorRT.sh"]
