name: "dinov2_ensemble"
platform: "ensemble"
max_batch_size: 32

input [
  {
    name: "IMAGE"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

output [
  {
    name: "features"
    data_type: TYPE_FP16    # changed to FP16 for consistency
    dims: [ -1 ]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "dinov2_preprocess"
      model_version: -1
      input_map { key: "IMAGE" value: "IMAGE" }
      output_map { key: "input" value: "preproc_out" }
    },
    {
      model_name: "dinov2"
      model_version: -1
      input_map  { key: "input"    value: "preproc_out" }
      output_map { key: "features" value: "features" }
    }
  ]
}
